/* 
 * <copyright> 
 *   
 *  Copyright 1999-2004 Object Services and Consulting, Inc. 
 *  under sponsorship of the Defense Advanced Research Projects 
 *  Agency (DARPA). 
 *  
 *  You can redistribute this software and/or modify it under the 
 *  terms of the Cougaar Open Source License as published on the 
 *  Cougaar Open Source Website (www.cougaar.org). 
 *  
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 *   
 * </copyright> 
 */ 
/* 
 */

package com.objs.surveyor.probemeister.bytecoder;

import java.awt.*;
import javax.swing.*;

/*
 * Stub_GetEventAttrsGUI2.java
 *
 * Created on June 12, 2002, 5:04 PM
 *
 * @author  Administrator
 */
public class Stub_GetEventAttrsGUI extends javax.swing.JDialog {

    static final int width = 405;
    static final int closeHeight = 285;
    static final int openHeight = 370;

    
    static Stub_GetEventAttrsGUI gui;
    static {
        gui = new Stub_GetEventAttrsGUI((java.awt.Frame)null, true);
        gui.setSize(width, closeHeight);
    }
    
    //Have one instance to save on memory.
    public static Stub_GetEventAttrsGUI gui() {return gui;}
 
    
    /** Creates new form Stub_GetEventAttrsGUI2 */
    public Stub_GetEventAttrsGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        getContentPane().setLayout(null);
        initComponents();
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   private void initComponents() {//GEN-BEGIN:initComponents
       bgLocation = new javax.swing.ButtonGroup();
       lTitle = new javax.swing.JLabel();
       lNote1 = new javax.swing.JLabel();
       lNote2 = new javax.swing.JLabel();
       jSeparator1 = new javax.swing.JSeparator();
       bLocationDetails = new javax.swing.JToggleButton();
       lEventType = new javax.swing.JLabel();
       lSubType = new javax.swing.JLabel();
       lMessage = new javax.swing.JLabel();
       vEventType = new javax.swing.JTextField();
       vEventSubType = new javax.swing.JTextField();
       vMessage = new javax.swing.JTextField();
       bOK = new javax.swing.JButton();
       rbAtStart = new javax.swing.JRadioButton();
       rbAtEnd = new javax.swing.JRadioButton();
       rbOffset = new javax.swing.JRadioButton();
       vOffset = new javax.swing.JTextField();
       bViewBytecode = new javax.swing.JButton();
       bViewSource = new javax.swing.JButton();
       
       
       getContentPane().setLayout(null);
       
       addWindowListener(new java.awt.event.WindowAdapter() {
           public void windowOpened(java.awt.event.WindowEvent evt) {
               openDialog(evt);
           }
           public void windowClosing(java.awt.event.WindowEvent evt) {
               closeDialog(evt);
           }
       });
               
       
       lTitle.setFont(new java.awt.Font("Dialog", 1, 18));
       lTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       lTitle.setText("ProbeStub Customization");
       getContentPane().add(lTitle);
       lTitle.setBounds(0, 10, 390, 30);
       
       lNote1.setFont(new java.awt.Font("Dialog", 0, 10));
       lNote1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       lNote1.setText("This Probe Stub requires customization.");
       getContentPane().add(lNote1);
       lNote1.setBounds(0, 40, 390, 14);
       
       lNote2.setFont(new java.awt.Font("Dialog", 0, 10));
       lNote2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       lNote2.setText("This information will be passed to the selected Probe Plug.");
       getContentPane().add(lNote2);
       lNote2.setBounds(0, 50, 400, 14);
       
       getContentPane().add(jSeparator1);
       jSeparator1.setBounds(130, 240, 240, 10);
       
       bLocationDetails.setFont(new java.awt.Font("Dialog", 0, 10));
       bLocationDetails.setText("Location Details...");
       bLocationDetails.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               bLocationDetailsActionPerformed(evt);
           }
       });
       
       getContentPane().add(bLocationDetails);
       bLocationDetails.setBounds(10, 230, 120, 20);
       
       lEventType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
       lEventType.setText("Event Type:");
       getContentPane().add(lEventType);
       lEventType.setBounds(20, 100, 80, 16);
       
       lSubType.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
       lSubType.setText("Event Subtype:");
       getContentPane().add(lSubType);
       lSubType.setBounds(10, 130, 90, 16);
       
       lMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
       lMessage.setText("Message:");
       getContentPane().add(lMessage);
       lMessage.setBounds(30, 160, 70, 16);
       
       getContentPane().add(vEventType);
       vEventType.setBounds(110, 100, 120, 20);
       
       getContentPane().add(vEventSubType);
       vEventSubType.setBounds(110, 130, 120, 20);
       
       
       getContentPane().add(vMessage);
       vMessage.setBounds(110, 160, 240, 20);
       
       bOK.setText("OK");
       bOK.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               bOK_Pressed(evt);
           }
       });
       
       getContentPane().add(bOK);
       bOK.setBounds(160, 200, 80, 26);
       
       rbAtStart.setSelected(true);
       rbAtStart.setText("At Start");
       bgLocation.add(rbAtStart);
       
       getContentPane().add(rbAtStart);
       rbAtStart.setBounds(30, 270, 68, 24);
       
       rbAtEnd.setText("At End");
       bgLocation.add(rbAtEnd);
       
       getContentPane().add(rbAtEnd);
       rbAtEnd.setBounds(110, 270, 61, 24);
       
       rbOffset.setText("At Bytecode Offset");
       bgLocation.add(rbOffset);
       
       getContentPane().add(rbOffset);
       rbOffset.setBounds(180, 270, 131, 24);
       
       vOffset.setText("0");
       
       getContentPane().add(vOffset);
       vOffset.setBounds(310, 270, 50, 20);
       vOffset.setText("0");
       
       bViewBytecode.setText("View Bytecode");
       bViewBytecode.setEnabled(false);
       getContentPane().add(bViewBytecode);
       bViewBytecode.setBounds(200, 310, 118, 26);
       
       bViewSource.setText("View Source");
       bViewSource.setEnabled(false);
       
       getContentPane().add(bViewSource);
       bViewSource.setBounds(70, 310, 106, 26);
       
       pack();
   }//GEN-END:initComponents

    private void bOK_Pressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOK_Pressed
        // Add your handling code here:
        this.setVisible(false); 
    }//GEN-LAST:event_bOK_Pressed

    private void bLocationDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLocationDetailsActionPerformed
        // If closed, expand window.
        if (bLocationDetails.isSelected()) // this.getHeight() == closeHeight)
            setSize(width, openHeight);        
        else  //it's open, so shrink window
            setSize(width, closeHeight);
        rbAtStart.invalidate();
        this.validate();
    }//GEN-LAST:event_bLocationDetailsActionPerformed


    /** Closes the dialog */
    private void openDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        rbAtStart.setSelected(true); //set this as the default
    }
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
//        new Stub_GetEventAttrsGUI2(new javax.swing.JFrame(), false).show();
        Stub_GetEventAttrsGUI gui = Stub_GetEventAttrsGUI.gui();
  //      gui.show();
    }

    public String getEvtString() {return this.vEventType.getText();}
    public String getSubEvtString() {return this.vEventSubType.getText();}
    public String getMsg() {return this.vMessage.getText();}

    public void setByteOffset(int _loc) {
     
        if (_loc == 0) 
            rbAtStart.setSelected(true);
        else if (_loc < 0)
            rbAtEnd.setSelected(true);
        else {
            rbOffset.setSelected(true);
            vOffset.setText(""+_loc);
        }
    }

    /* Returns 0 for start of method, -1 for end of method, and a positive
     * integer (entered by the user) as a byte offset
     */
    public int    getByteOffset() {
        if (this.rbAtStart.isSelected()) 
            return 0;
        else if (this.rbAtEnd.isSelected())
            return -1;
        else if (rbOffset.isSelected()) {
            String sval = vOffset.getText();
            int val = 0; //default to start
            try {
                val = Integer.parseInt(sval);
            } catch (NumberFormatException nfe) {
            }
            return val;
        }
        else //default to insert at start
            return 0;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLocation;
    private javax.swing.JLabel lTitle;
    private javax.swing.JLabel lNote1;
    private javax.swing.JLabel lNote2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToggleButton bLocationDetails;
    private javax.swing.JLabel lEventType;
    private javax.swing.JLabel lSubType;
    private javax.swing.JLabel lMessage;
    private javax.swing.JTextField vEventType;
    private javax.swing.JTextField vEventSubType;
    private javax.swing.JTextField vMessage;
    private javax.swing.JButton bOK;
    private javax.swing.JRadioButton rbAtStart;
    private javax.swing.JRadioButton rbAtEnd;
    private javax.swing.JRadioButton rbOffset;
    private javax.swing.JTextField vOffset;
    private javax.swing.JButton bViewBytecode;
    private javax.swing.JButton bViewSource;
    // End of variables declaration//GEN-END:variables

}
