/* 
 * <copyright> 
 *   
 *  Copyright 1999-2004 Object Services and Consulting, Inc. 
 *  under sponsorship of the Defense Advanced Research Projects 
 *  Agency (DARPA). 
 *  
 *  You can redistribute this software and/or modify it under the 
 *  terms of the Cougaar Open Source License as published on the 
 *  Cougaar Open Source Website (www.cougaar.org). 
 *  
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY 
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 *   
 * </copyright> 
 */ 


package com.objs.surveyor.probemeister.probe;

import java.awt.*;
import javax.swing.*;

public class ProbeInfoDialog extends javax.swing.JDialog
{
	public ProbeInfoDialog(Frame parent)
	{
		super(parent);
		
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(null);
		setSize(476,363);
		setVisible(false);
		jlTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jlTitle.setText("Probe Information");
		getContentPane().add(jlTitle);
		jlTitle.setFont(new Font("Dialog", Font.BOLD, 14));
		jlTitle.setBounds(60,12,360,24);
		jlID.setText("Probe ID:");
		getContentPane().add(jlID);
		jlID.setBounds(24,37,63,24);
		jlType.setText("Type:");
		getContentPane().add(jlType);
		jlType.setBounds(24,69,63,24);
		jlDesc.setText("Description:");
		getContentPane().add(jlDesc);
		jlDesc.setBounds(24,101,77,23);
		jlLocation.setText("Location");
		getContentPane().add(jlLocation);
		jlLocation.setBounds(24,132,63,24);
		jlClass.setText("Class:");
		getContentPane().add(jlClass);
		jlClass.setBounds(42,153,47,25);
		jlMethod.setText("Method:");
		getContentPane().add(jlMethod);
		jlMethod.setBounds(42,179,47,23);
		jlOffset.setText("Current Bytecode Offset:");
		getContentPane().add(jlOffset);
		jlOffset.setBounds(43,203,150,23);
		getContentPane().add(vID);
		vID.setForeground(java.awt.Color.black);
		vID.setBounds(93,37,225,24);
		getContentPane().add(vType);
		vType.setForeground(java.awt.Color.black);
		vType.setBounds(93,69,225,24);
		getContentPane().add(vDesc);
		vDesc.setForeground(java.awt.Color.black);
		vDesc.setBounds(112,102,338,42);
                vDesc.setLineWrap(true);
                vDesc.setEditable(false);
                vDesc.setWrapStyleWord(true);
		getContentPane().add(vClassLoc);
		vClassLoc.setForeground(java.awt.Color.black);
		vClassLoc.setBounds(111,153,320,25);
		getContentPane().add(vMethodLoc);
		vMethodLoc.setForeground(java.awt.Color.black);
		vMethodLoc.setBounds(111,179,325,23);
		getContentPane().add(vOffsetLoc);
		vOffsetLoc.setForeground(java.awt.Color.black);
		vOffsetLoc.setBounds(198,203,30,22);
		jbOK.setText("OK");
		jbOK.setActionCommand("OK");
		getContentPane().add(jbOK);
		jbOK.setBounds(199,324,78,28);
		JScrollPane1.setOpaque(true);
		getContentPane().add(JScrollPane1);
		JScrollPane1.setBounds(24,264,421,48);
		JScrollPane1.getViewport().add(vParams);
		vParams.setBounds(0,0,418,45);
		jlParams.setText("Parameters");
		getContentPane().add(jlParams);
		jlParams.setBounds(24,237,77,24);
		//}}
	
		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		jbOK.addActionListener(lSymAction);
		//}}
	}

	public ProbeInfoDialog()
	{
		this((Frame)null);
	}

	public ProbeInfoDialog(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	static public void main(String args[])
	{
		(new ProbeInfoDialog()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets
		Insets insets = getInsets();
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JLabel jlTitle = new javax.swing.JLabel();
	javax.swing.JLabel jlID = new javax.swing.JLabel();
	javax.swing.JLabel jlType = new javax.swing.JLabel();
	javax.swing.JLabel jlDesc = new javax.swing.JLabel();
	javax.swing.JLabel jlLocation = new javax.swing.JLabel();
	javax.swing.JLabel jlClass = new javax.swing.JLabel();
	javax.swing.JLabel jlMethod = new javax.swing.JLabel();
	javax.swing.JLabel jlOffset = new javax.swing.JLabel();
	javax.swing.JLabel vID = new javax.swing.JLabel();
	javax.swing.JLabel vType = new javax.swing.JLabel();
	javax.swing.JTextArea vDesc = new javax.swing.JTextArea();
	javax.swing.JLabel vClassLoc = new javax.swing.JLabel();
	javax.swing.JLabel vMethodLoc = new javax.swing.JLabel();
	javax.swing.JLabel vOffsetLoc = new javax.swing.JLabel();
	javax.swing.JButton jbOK = new javax.swing.JButton();
	javax.swing.JScrollPane JScrollPane1 = new javax.swing.JScrollPane();
	javax.swing.JList vParams = new javax.swing.JList();
	javax.swing.JLabel jlParams = new javax.swing.JLabel();
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
			Object object = event.getSource();
			if (object == jbOK)
				jbOK_actionPerformed(event);
		}
	}

	void jbOK_actionPerformed(java.awt.event.ActionEvent event)
	{
		// to do: code goes here.
	    this.setVisible(false);
	}
	
	public void configure(String _id, String _type, String _desc, 
	                      String _cLoc, String _mLoc, String _oLoc,
	                      String[] params) {
	
	    this.vID.setText(_id);     //set probe ID
	    this.vType.setText(_type); //set type
        this.vDesc.setText(_desc); //set description
        
        this.vClassLoc.setText(_cLoc);
        this.vMethodLoc.setText(_mLoc);
        this.vOffsetLoc.setText(_oLoc);
        
        this.vParams.setListData(params);
    }
	
}